#
# Build the slooh explorer and publish as a zip
#

name: Duplicate Files

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_VERSION: "1.0.${{ github.run_number }}"
  CHOCOLATELY_PACKAGE: "chocolateley\\duplicate-files.nuspec"
  RELEASE_CHOCOLATELY: false

jobs:

  build:
    name: Build
    runs-on: windows-latest  

    steps:
    # - name: List env
    #  run: env
      
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    
    # Compile the solution
    - name: Compile solution
      run: dotnet build src\DuplicateFiles.slnx -c Release -o output -p:Version=${{ env.BUILD_VERSION }} -p:AssemblyVersion=${{ env.BUILD_VERSION }} -p:FileVersion=${{ env.BUILD_VERSION }} -p:InformationalVersion=${{ env.BUILD_VERSION }}

    - name: Remove unnecessary files
      run: del output\*.pdb,output\*.dev.json,output\*.deps.json 
    
    - name: Upload output
      uses: actions/upload-artifact@v6
      with:
        name: output
        path: output
      
  pack_release:
    name: Pack Release
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download output
      uses: actions/download-artifact@v8
      with:
        name: output
        path: output
    
    - name: Pack binaries
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: 'binary.zip'
        path: output
        type: 'zip'

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: binary
        path: binary.zip
  
  pack_chocolately:
    name: Pack Chocolateley
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Download output
      uses: actions/download-artifact@v8
      with:
        name: output
        path: output

    - name: Patch chocolately package
      run: |         
        $xml = [xml](Get-Content ${{ env.CHOCOLATELY_PACKAGE }})
        $xml.DocumentElement.metadata.version = "${{ env.BUILD_VERSION }}"
        $xml.Save("${{ env.CHOCOLATELY_PACKAGE }}")
        copy output\* chocolateley\tools -Recurse        

    - name: Create chocolately package
      uses: crazy-max/ghaction-chocolatey@v2
      with:
         args: pack ${{ env.CHOCOLATELY_PACKAGE }}        

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: artifact
        path: duplicate-files.${{ env.BUILD_VERSION }}.nupkg

  push_release:
    name: Push Release
    needs: [pack_release, pack_chocolately]
    runs-on: windows-latest

    steps:
    - name: Download binary artifact
      uses: actions/download-artifact@v8
      with:
        name: binary

    - name: Download cocolately artifact
      uses: actions/download-artifact@v8
      with:
        name: artifact
        
    - name: Rename binary artifact
      run: mv binary.zip "Duplicate-Files-Binary-${{ env.BUILD_VERSION }}.zip"

    - name: Rename chocolately artifact
      run: mv duplicate-files.${{ env.BUILD_VERSION }}.nupkg "Duplicate-Files-Chocolately-${{ env.BUILD_VERSION }}.nupkg"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          "Duplicate-Files-Binary-${{ env.BUILD_VERSION }}.zip"
          "Duplicate-Files-Chocolately-${{ env.BUILD_VERSION }}.nupkg"
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push_chocolately:
    name: Push Chocolately
    needs: pack_chocolately
    runs-on: windows-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        name: artifact
    - name: Push package to chocolately
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: push duplicate-files.${{ env.BUILD_VERSION }}.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATELY_TOKEN }}
